### ISSUE TITLE
Stuck on page render.

### ISSUE THREAD

**Issue by NayanKhedkar** [LearnChamp/adapt-flippableCards#1]
I added this component to course. While launch the page it's stuck.

**Comment by lc-thomasberger** [comment]
What Version of the Framework do you use?

**Comment by NayanKhedkar** [comment]
v3.0.0

**Comment by NayanKhedkar** [comment]
can you change this https://github.com/LearnChamp/adapt-flippableCards/blob/master/js/flippableCardModel.js#L3   with 'core/js/models/itemsComponentModel'

**Comment by NayanKhedkar** [comment]
I think some functions of **itemsComponentModel**  not  get available in the file **flippableCardView.js**  that's why it may be stuck.

**Comment by lc-thomasberger** [comment]
Yes, it is using the itemsModel and not the itemsCollection. 
It also mentions in the [readme](https://github.com/LearnChamp/adapt-flippableCards#limitations) that Version 3 of the Framework is currently not supported.
Sorry, unfortunately I am not able to update the component to support V3.

**Comment by NayanKhedkar** [comment]
No problem :smiley:
